-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PESSOA (
CPF INTEGER,
Email VARCHAR(10),
ID_Pessoa INTEGER PRIMARY KEY,
Nome VARCHAR(10),
Dat_Nascimento DATETIME,
ID_Tipo_pessoa INTEGER
)

CREATE TABLE Tipo_Pessoa (
ID_Tipo_pessoa INTEGER PRIMARY KEY,
Tipo VARCHAR(10)
)

CREATE TABLE COMPRA (
ID_Compra INTEGER PRIMARY KEY,
Tipo_Pagamento VARCHAR(10),
Dat_Compra DATETIME,
ID_Pessoa INTEGER,
FOREIGN KEY(ID_Pessoa) REFERENCES PESSOA (ID_Pessoa)
)

CREATE TABLE ITEM COMPRA (
ID_ITEM INTEGER PRIMARY KEY,
Qnt_Item INTEGER,
ID_Compra INTEGER,
ID_Produto INTEGER,
FOREIGN KEY(ID_Compra) REFERENCES COMPRA (ID_Compra)
)

CREATE TABLE FAVORITA (
ID_Produto INTEGER,
ID_Pessoa INTEGER,
FOREIGN KEY(ID_Pessoa) REFERENCES PESSOA (ID_Pessoa)
)

CREATE TABLE PRODUTOS (
Nome_Produto VARCHAR(10),
Qnt_Produto INTEGER,
Preço_Produto DECIMAL(10),
Tipo_Produto VARCHAR(10),
ID_Produto INTEGER PRIMARY KEY
)

CREATE TABLE ITEM COMBO (
ID_Item_Combo VARCHAR(10) PRIMARY KEY,
ID_Produto INTEGER,
ID_Combo INTEGER,
FOREIGN KEY(ID_Produto) REFERENCES PRODUTOS (ID_Produto)
)

CREATE TABLE COMBOS (
Preço_Combo VARCHAR(10),
Nome_Combo INTEGER,
ID_Combo INTEGER PRIMARY KEY
)

ALTER TABLE PESSOA ADD FOREIGN KEY(ID_Tipo_pessoa) REFERENCES Tipo_Pessoa (ID_Tipo_pessoa)
ALTER TABLE ITEM COMPRA ADD FOREIGN KEY(ID_Produto) REFERENCES PRODUTOS (ID_Produto)
ALTER TABLE FAVORITA ADD FOREIGN KEY(ID_Produto) REFERENCES PRODUTOS (ID_Produto)
ALTER TABLE ITEM COMBO ADD FOREIGN KEY(ID_Combo) REFERENCES COMBOS (ID_Combo)
